### ISSUE TITLE
Need more than 5 minutes limit that Lambda gives us for whole Bibles

### ISSUE THREAD

**Issue by richmahn** [unfoldingWord-dev/door43.org#215]
## Story

As a user I want to be able to have a repo of the whole Bible to be converted from USFM.

Currently, the 5 minute limit of Lambda, which is the max, will only let one convert from USFM to HTML as far as the book of Psalms before it cut off and the process terminated.

We need to research how we can do this differently, such as by each book, or another process that manages this.

For reference: https://serifandsemaphore.io/aws-lambda-going-beyond-5-minutes-34e381e71231

**Comment by jag3773** [comment]
My recommendation is that we split up larger projects into sections and fire off multiple mini-conversion lambdas that dump their data into the specified location.  Possibly `tx-manager` could figure this out.  In the case of the `usfm2html`, there is no reason why we can't convert each book individually and then have a cleanup process to merge them together.

Alternately, I wonder why it takes so long to process USFM to HTML, possibly it's worth some effort to optimize the conversion utility?

**Comment by ethantkoenig** [comment]
FWIW: I've run a few benchmarking tests on develop, and they seem to indicate that tx-usfm2html_convert is 5-6 times faster than rich-usfm2html_convert. For instance, running Exodus, Numbers, Deuteronomy, Judges, Nehemiah and Job took 11 seconds on tx-usfm2html_convert and 64 seconds with rich-usfm2html_convert.

This is of course under the assumption that rich-usfm2html_convert is what is currently being used. I assume this is the case, since tx-simple-usfm2html_convert seems to be having dependency issues.

**Comment by richmahn** [comment]
It's tx-simple-usfm2htlml

**Comment by richmahn** [comment]
It's tx-simple-usfm2html that's currently being used.

**Comment by richmahn** [comment]
Again, need to be making sure we are using all the customizations we have in USFM-Tools we have for the custom tags we use and the footnote rendering I just added, which is what tx-simple-usfm2html users

**Comment by richmahn** [comment]
I had thought we could do one file by one, and then somehow the converter does a call back to tx-manager when done, rather than tx-manager waiting (as it currently does), thus currently we actually have two lambda functions terminating, the tx-manager_startJob and the conversion function. We maybe should even make this so that, like my tx-door43_deploy, it just goes by files dumped in a bucket/key....if it sees a file.usfm file, with a file.usfm.meta (maybe data about the type of Bible or resource), the converter knows what to do, converts it, places a file.html when done, and then either does a callback, or a file.html file in S3 triggers the tx-manager to check on the given job to see if all html files are done....I kind of like the latter. Hope that makes sense.

**Comment by richmahn** [comment]
This of course would mean going back to not zipping up the files, but use the job_id as the key for file (tx/job/pre/a39dlz0d9d093l1/01-GEN.usfm, tx/job/pre/a39dlz0d9d093l1/02-EXO.usfm, etc.) and the files then go to tx/job/converted/01-GEN.html, etc. tX-manager either records how many files there were, or could compare pre/ with converted/ and see if each file was done, etc.

**Comment by richmahn** [comment]
@ethankoenig what were the dependency issues? I've never had a problem with tx-simple-usfm2html

**Comment by jag3773** [comment]
There is something called a continuation token that is discussed here: http://docs.aws.amazon.com/codepipeline/latest/userguide/how-to-lambda-integration.html .  From my reading it sounds like the initial Lambda process could kick off a whole bunch of smaller processes and the master/initial process could get a continuation token to check in on the smaller tasks until they are all complete.

Something at least to look into.

**Comment by jag3773** [comment]
Fixed in #556

**Comment by richmahn** [comment]
Kind of fixed, but it appears there is still a problem with it all working with more than 50 books, a timing thing with piecing together everything. I could be wrong though. @PhotoNomad0 what do you feel the status of this is? Is there still an issue getting the whole Bible converted even breaking it down into 66 jobs?

**Comment by richmahn** [comment]
I believe that it takes about 6 seconds per book to separate its USFM file, zip it up, send the request to the tx-Manager API Gateway and wait for a response before going on to the next book...thus 6*50 = 300 seconds = 5 minutes. So I guess the client breaking this apart now has a timeout issue?
